version: "3.3"

services:
  react:
    build:
      context: .
    image: react_dev
    container_name: react_dev
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
