version: "3.3"
services:
  frontend:
    build:
      context: .
      ports:
        - "3000:3000"
      container_name: react-frontend
      stdin_open: true
      volumes:
        - ./
        - ./node_modules
      command: npm start
